Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.synced_folder "./", "/var/www/app"
    config.vm.network :private_network, ip: "192.168.50.30"
    config.vm.provision "file", source: "./vagrant_stuff/siteObservable.conf", destination: "/home/ubuntu/siteObservable.conf"
    config.vm.provision "file", source: "./vagrant_stuff/userscript.sh", destination: "/home/ubuntu/userscript.sh"
    config.vm.provision :shell, path: "./vagrant_stuff/provision.sh"
end
