development:
  adapter: postgresql
  encoding: unicode
  database: todo_base
  pool: 2
  username: angel
  password: angel
  host: 192.168.50.15

production:
  adapter: postgresql
  encoding: unicode
  database: todo_base
  pool: 2
  username: angel
  password: angel
  host: 192.168.50.15
  