Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.4"
  config.vm.network "private_network", ip: "192.168.50.15"
  config.vm.provision "file", source: "./vagrant_stuff/rubyserver.service", destination: "/home/vagrant/rubyserver.service"
  config.vm.provision "file", source: "./vagrant_stuff/userscript.sh", destination: "/home/vagrant/userscript.sh"
  config.vm.provision "file", source: "./vagrant_stuff/.udev-mount-restart-services.sh", destination: "/home/vagrant/.udev-mount-restart-services.sh"
  config.vm.provision "file", source: "./vagrant_stuff/50-vagrant-mount.rules", destination: "/home/vagrant/50-vagrant-mount.rules"
  config.vm.provision :shell, path: "./vagrant_stuff/provision.sh"
end
