Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "./", "/var/www/masterapp"
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.provision "file", source: "./vagrant_stuff/default", destination: "/home/ubuntu/default"
  config.vm.provision "file", source: "./vagrant_stuff/userscript.sh", destination: "/home/ubuntu/userscript.sh"
  config.vm.provision :shell, path: "./vagrant_stuff/provision.sh"
end
