Vagrant.configure("2") do |config|
    config.vm.box = "ogarcia/archlinux-x64"
    config.vm.network :private_network, ip: "192.168.50.20"
    config.vm.provision :shell, path: "provision.sh"

    config.vm.synced_folder "./", "/srv/http"
end
